#!/bin/bash



ubuntu=`cat /etc/os-release | grep -o "ubuntu" | head -1`
fedora=`cat /etc/os-release | grep -o "fedora" | head -1`
suse=`cat /etc/os-release | grep -o "suse" | head -1`
rocky=`cat /etc/os-release | grep -o "Rocky" | head -1`


if [ "$ubuntu" == "ubuntu" ];then
	sudo apt update 
	sudo apt install clamav clamav-daemon -y
	echo "clamAV installed on Ubuntu"
	sudo systemctl stop clamav-freshclam
	sudo freshclam
	sudo systemctl start clamav-freshclam
	echo "clamAV Database Downloaded"

	sudo apt update 
	sudo apt install wget -y
	cd /tmp/ 
	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar xfz maldetect-current.tar.gz
	cd maldetect-1.6.4
	./install.sh
	cd


	## Create config File for Maldet
	sudo echo -e """# To enable the email notification.\n
	email_alert='1'\n\n
	# Specify the email address on which you want to receive an email notification. \n
	email_addr='user@domain.com'\n\n
	# Enable the LMD signature autoupdate.\n
	autoupdate_version='1'\n\n
	# Enable the daily automatic scanning.\n
	cron_daily_scan='1'\n\n
	# Allows non-root users to perform scans.\n
	scan_user_access='1'\n\n
	# Move hits to quarantine & alert\n
	quarantine_hits='1'\n\n
	# Clean string based malware injections.\n
	quarantine_clean='0'\n\n
	# Suspend user if malware found.\n
	quarantine_suspend_user='1'\n\n
	# Minimum userid value that be suspended\n
	quarantine_suspend_user_minuid='500'\n\n
	# Enable Email Alerting\n
	email_alert='1'\n\n
	# Email Address in which you want to receive scan reports\n
	email_addr='you@domain.com'\n\n
	# Use with ClamAV\n
	scan_clamscan='1'\n\n
	# Enable scanning for root-owned files. Set 1 to disable.\n
	scan_ignore_root='0'\n\n

	""" > /usr/local/maldetect/conf.maldet


	sudo apt install sshfs -y

	sclamscan="/usr/sbin/clamscan"
	bclamscan="/usr/bin/clamscan"

	if [ -f "$sclamscan" ] || [ -f "$bclamscan" ];then
		echo "ClamAV Installed Successfully [ OK ]"
	else
		echo "ERROR !!! ClamAV Not Installed Successfully"
	fi


	bmaldet="/usr/bin/maldet"
	smaldet="/usr/sbin/maldet"

	if [ -f "$bmaldet" ] || [ -f "$smaldet" ];then

		echo "Maldet Installed Successfully [ OK ]"
	else
		echo "ERROR !!! Not Installed Successfully"
	fi

elif [ "$fedora" == "fedora" ];then

	sudo dnf upgrade --refresh
	sudo dnf install clamav clamd clamav-update -y
	echo "clamAV installed"
	sudo freshclam
	sudo systemctl enable --now clamav-freshclam
	echo "ClamAV Database Updated"
	
	
	sudo dnf install wget -y
	cd /tmp/ 
	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar xfz maldetect-current.tar.gz
	cd maldetect-1.6.4
	./install.sh
	cd


	## Create config File for Maldet
	sudo echo -e """# To enable the email notification.\n
	email_alert='1'\n\n
	# Specify the email address on which you want to receive an email notification. \n
	email_addr='user@domain.com'\n\n
	# Enable the LMD signature autoupdate.\n
	autoupdate_version='1'\n\n
	# Enable the daily automatic scanning.\n
	cron_daily_scan='1'\n\n
	# Allows non-root users to perform scans.\n
	scan_user_access='1'\n\n
	# Move hits to quarantine & alert\n
	quarantine_hits='1'\n\n
	# Clean string based malware injections.\n
	quarantine_clean='0'\n\n
	# Suspend user if malware found.\n
	quarantine_suspend_user='1'\n\n
	# Minimum userid value that be suspended\n
	quarantine_suspend_user_minuid='500'\n\n
	# Enable Email Alerting\n
	email_alert='1'\n\n
	# Email Address in which you want to receive scan reports\n
	email_addr='you@domain.com'\n\n
	# Use with ClamAV\n
	scan_clamscan='1'\n\n
	# Enable scanning for root-owned files. Set 1 to disable.\n
	scan_ignore_root='0'\n\n

	""" > /usr/local/maldetect/conf.maldet
	
	sudo yum install epel-release -y
	sudo yum makecache fast
	sudo dnf install sshfs -y

	sclamscan="/usr/sbin/clamscan"
	bclamscan="/usr/bin/clamscan"

	if [ -f "$sclamscan" ] || [ -f "$bclamscan" ];then
		echo "ClamAV Installed Successfully [ OK ]"
	else
		echo "ERROR !!! ClamAV Not Installed Successfully"
	fi


	bmaldet="/usr/bin/maldet"
	smaldet="/usr/sbin/maldet"

	if [ -f "$bmaldet" ] || [ -f "$smaldet" ];then

		echo "Maldet Installed Successfully [ OK ]"
	else
		echo "ERROR !!! Not Installed Successfully"
	fi



elif [ "$suse" == "suse" ];then
	
	# clamAV
	sudo zypper install pcre-devel clamav clamav-database clamav-nodb clamz
	echo "(1/4) .......... clamAV Installed"
	sudo systemctl  stop freshcalam
	sudo freshclam

	sudo zypper install wget -y
	cd /tmp/ 
	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar xfz maldetect-current.tar.gz
	cd maldetect-1.6.4
	./install.sh
	cd


	## Create config File for Maldet
	sudo echo -e """# To enable the email notification.\n
	email_alert='1'\n\n
	# Specify the email address on which you want to receive an email notification. \n
	email_addr='user@domain.com'\n\n
	# Enable the LMD signature autoupdate.\n
	autoupdate_version='1'\n\n
	# Enable the daily automatic scanning.\n
	cron_daily_scan='1'\n\n
	# Allows non-root users to perform scans.\n
	scan_user_access='1'\n\n
	# Move hits to quarantine & alert\n
	quarantine_hits='1'\n\n
	# Clean string based malware injections.\n
	quarantine_clean='0'\n\n
	# Suspend user if malware found.\n
	quarantine_suspend_user='1'\n\n
	# Minimum userid value that be suspended\n
	quarantine_suspend_user_minuid='500'\n\n
	# Enable Email Alerting\n
	email_alert='1'\n\n
	# Email Address in which you want to receive scan reports\n
	email_addr='you@domain.com'\n\n
	# Use with ClamAV\n
	scan_clamscan='1'\n\n
	# Enable scanning for root-owned files. Set 1 to disable.\n
	scan_ignore_root='0'\n\n

	""" > /usr/local/maldetect/conf.maldet


	sudo zypper -n install sshfs

	sclamscan="/usr/sbin/clamscan"
	bclamscan="/usr/bin/clamscan"

	if [ -f "$sclamscan" ] || [ -f "$bclamscan" ];then
		echo "ClamAV Installed Successfully [ OK ]"
	else
		echo "ERROR !!! ClamAV Not Installed Successfully"
	fi


	bmaldet="/usr/bin/maldet"
	smaldet="/usr/sbin/maldet"

	if [ -f "$bmaldet" ] || [ -f "$smaldet" ];then

		echo "Maldet Installed Successfully [ OK ]"
	else
		echo "ERROR !!! Not Installed Successfully"
	fi



elif [ "$rocky" == "Rocky" ];then
	dnf install epel-release
	dnf install -y clamav clamd clamav-update
	echo "clamAV installed"
	systemctl stop clamav-freshclam
	sudo freshclam
	sudo systemctl enable --now clamav-freshclam
	echo "ClamAV Database Updated"
	
	
	sudo dnf install wget -y
	cd /tmp/ 
	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar xfz maldetect-current.tar.gz
	cd maldetect-1.6.4
	./install.sh
	cd


	## Create config File for Maldet
	sudo echo -e """# To enable the email notification.\n
	email_alert='1'\n\n
	# Specify the email address on which you want to receive an email notification. \n
	email_addr='user@domain.com'\n\n
	# Enable the LMD signature autoupdate.\n
	autoupdate_version='1'\n\n
	# Enable the daily automatic scanning.\n
	cron_daily_scan='1'\n\n
	# Allows non-root users to perform scans.\n
	scan_user_access='1'\n\n
	# Move hits to quarantine & alert\n
	quarantine_hits='1'\n\n
	# Clean string based malware injections.\n
	quarantine_clean='0'\n\n
	# Suspend user if malware found.\n
	quarantine_suspend_user='1'\n\n
	# Minimum userid value that be suspended\n
	quarantine_suspend_user_minuid='500'\n\n
	# Enable Email Alerting\n
	email_alert='1'\n\n
	# Email Address in which you want to receive scan reports\n
	email_addr='you@domain.com'\n\n
	# Use with ClamAV\n
	scan_clamscan='1'\n\n
	# Enable scanning for root-owned files. Set 1 to disable.\n
	scan_ignore_root='0'\n\n

	""" > /usr/local/maldetect/conf.maldet
	
	sclamscan="/usr/sbin/clamscan"
	bclamscan="/usr/bin/clamscan"

	if [ -f "$sclamscan" ] || [ -f "$bclamscan" ];then
		echo "ClamAV Installed Successfully [ OK ]"
	else
		echo "ERROR !!! ClamAV Not Installed Successfully"
	fi


	bmaldet="/usr/bin/maldet"
	smaldet="/usr/sbin/maldet"

	if [ -f "$bmaldet" ] || [ -f "$smaldet" ];then

		echo "Maldet Installed Successfully [ OK ]"
	else
		echo "ERROR !!! Not Installed Successfully"
	fi






else
	echo "!!! Your Distro Not Supported !!!"
	sleep 1
	exit 0
fi




