#!/usr/bin/bash


## Created Directory for Remote Files 

SCAN_PATH="/tmp/wpscan"

if [ -d "SCAN_PATH" ];then
	true
else
	mkdir /tmp/wpscan
fi


printf "Enter Server Username : "
read server_user

printf "server_ip"
read server_ip


printf "Your WordPress Directory :"
read wp_path


## Mount Remove Directory to Local Directory

sshfs $server_user@$server_ip:$wp_path /tmp/wpscan

# Scan Direcoty With Linux Malware Detect

sudo maldet -a /tmp/wpscan

# Scan Directory With ClamAV

sudo clamscan --infected --recursive --remove /tmp/wpscan

# UnMount Mounted Directory

fusermount -u /tmp/wpscan
